### ISSUE TITLE
I drop the svg file and it show me error

### ISSUE THREAD

**Issue by lindexi** [taherz/SVGViewerUWP#1]
When I drop the svg file to app ,say that "the dropped folder/file do not contain Svg"

![image](https://cloud.githubusercontent.com/assets/16054566/21070655/08d7ddf8-bec5-11e6-9289-cc98613b1d32.png)

![image](https://cloud.githubusercontent.com/assets/16054566/21070649/ea2d0c66-bec4-11e6-8425-26cc8e0702fb.png)

When selected the Folder that contain the svg file ,the app give a message that "path folder does not contain svg"

![image](https://cloud.githubusercontent.com/assets/16054566/21070664/402d19f8-bec5-11e6-871d-c13d793de8e8.png)

![image](https://cloud.githubusercontent.com/assets/16054566/21070668/4a74fc00-bec5-11e6-9ed6-c71d46cacacc.png)

**Comment by taherz** [comment]
Thank lindexi for let me know about this big issue.

I had some svg document which I used for testing and all of them worked with me !!!

then I download some svg docs from different websites and find that svg with node "<!DOCTYPE...." are not working with the app.

I have pushed the fixes. please pull the latest commit and test it.

please update me with the result.

**Comment by lindexi** [comment]
Thx your open-source app that make me learn some knowledge about svg.
